name: Python Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with pylint
      run: |
        pylint --disable=C0111,C0103,C0303,C0330 **/*.py
    
    - name: Run tests
      run: |
        # Add test command here when tests are available
        echo "No tests configured yet" 